server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tangsongxy/tensquare_config.git
  rabbitmq:
    host: 132.232.104.247
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh