server:
  port: 9015
spring:
  application:
    name: tensquare-user-crawler #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.104.247:3306/tensquare_user?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 132.232.104.247
userImg:
  save:
    path: E:\360用户文件\avatar